### ISSUE TITLE
qgrid throws exception and locks up widget when sorting columns with mixed datatypes

### ISSUE THREAD

**Issue by akapocsi** [quantopian/qgrid#133]
When sorting a column of a DataFrame with mixed datatypes, the following exception is raised by pandas:

```
[IPKernelApp] ERROR | '>' not supported between instances of 'float' and 'str'
[IPKernelApp] ERROR | Unhandled exception while handling msg
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\qgrid\grid.py", line 743, in _handle_qgrid_msg
    self._handle_qgrid_msg_helper(content)
  File "C:\Anaconda3\lib\site-packages\qgrid\grid.py", line 805, in _handle_qgrid_msg_helper
    self._update_sort()
  File "C:\Anaconda3\lib\site-packages\qgrid\grid.py", line 491, in _update_sort
    inplace=True
  File "C:\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3201, in sort_values
    na_position=na_position)
  File "C:\Anaconda3\lib\site-packages\pandas\core\sorting.py", line 247, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '>' not supported between instances of 'float' and 'str'
```

This is the expected behavior from pandas, but qgrid should prevent this from locking up the widget.

Here is a reproducible example:

```
import pandas as pd
import qgrid
df = pd.DataFrame({'A': [1.2, 'xy', 4]})
qgrid_widget = qgrid.QgridWidget(df=df, show_toolbar=True)
qgrid_widget
```

Clicking on the header of column 'A' or attempting to resize the column will raise the exception.

**Comment by TimShawver** [comment]
Thanks for the report...I wasn't aware of this case.
