### ISSUE TITLE
Cannot get pip install -e working for local install

### ISSUE THREAD

**Issue by ruidc** [quantopian/qgrid#235]
### Environment

* Operating System: Linux
* Python Version: `Python 2.7.15 :: Anaconda, Inc.`
* How did you install Qgrid: `git clone as per https://github.com/quantopian/qgrid#running-from-source--testing-your-changes`
* Python packages:
```
notebook==5.7.0
git+https://github.com/quantopian/qgrid.git@4fbe5921fd4465b73ae3d43aa6bc5cadfad8baa8#egg=qgrid
jupyter-client==5.2.3
jupyter-core==4.4.0
```
* Jupyter lab packages (if applicable): `Not Applicable`

### Description of Issue
Raises the file missing error below. 
If I copy the 2 JS files (index.js, extension.js) manually from js/src to the expected qgrid/static directory, The install succeeds but I instead get a JS console error in browser:
```
ReferenceError: module is not defined
	http://localhost:8000/user/r.costa/nbextensions/qgrid/extension.js:17:1
```
* What did you expect to happen?
 install succeed, grid to work
* What happened instead?
as above. Running with the conda/pip+pypi version works fine, but i want to make and test changes
```
Obtaining file:///tmp/qgrid
    Complete output from command python setup.py egg_info:
    setup.py entered
    $PATH=/opt/conda/envs/platform/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    running egg_info
    running jsdeps
    5.6.0
    5.6.0
    Installing build dependencies with npm.  This may take a while...
    npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
    npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
    npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
    npm WARN lifecycle qgrid@1.1.1~prepublish: cannot run in wd %s %s (wd=%s) qgrid@1.1.1 webpack /tmp/qgrid/js
    npm WARN ajv-keywords@3.3.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN qgrid@1.1.1 No license field.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    
    up to date in 2.283s
    rebuilding js and css failed
    missing files: ['/tmp/qgrid/qgrid/static/extension.js', '/tmp/qgrid/qgrid/static/index.js']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/qgrid/setup.py", line 181, in <module>
        setup(**setup_args)
      File "/opt/conda/envs/platform/lib/python2.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/envs/platform/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/opt/conda/envs/platform/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/platform/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/qgrid/setup.py", line 48, in run
        raise e
    ValueError: Missing file: /tmp/qgrid/qgrid/static/extension.js
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/qgrid/
```
### Reproduction Steps

1. follow the steps 1+2 here: https://github.com/quantopian/qgrid#running-from-source--testing-your-changes
2.after getting the above error, copy the 2 missing JS files  (index.js, extension.js) from  js/src to the expected qgrid/static directory,
3. repeat step 2 and continue
4. open a notebook and attempt to display the grid - get no error other than the above in console.
...

### What steps have you taken to resolve this already?
Uninstalled and cleaned. Tested that the pypi version 1.1.1 works. Tried incrementing version numbers
...

### Anything else?

...

**Comment by ruidc** [comment]
Recreating everything from scratch fixed the 2nd problem, but the 2 JS files still require manual copying, and unsure if this is correctly handled on node, as I cannot see my JS code from the browser

**Comment by 0xmjk** [comment]
Not sure why this files are not being copied, but my commit above hacks around it... Can you check if it works for you too?
