### ISSUE TITLE
qgrid on Google Colab?

### ISSUE THREAD

**Issue by rcontesti** [quantopian/qgrid#263]
Has anybody been able to to make Qgrid work on google colab? Thanks.

**Comment by Berowne** [comment]
Also having trouble...
after folowing above (and also trying pip install qgrid --user) 

> !pip install qgrid --user
> !jupyter nbextension enable --py --sys-prefix widgetsnbextension
> !jupyter nbextension enable --py --sys-prefix qgrid


I get the following error

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named qgrid

**Comment by charlie17** [comment]
Looks like they've [got wheels in motion](https://github.com/googlecolab/colabtools/issues/498#issuecomment-910755873)

**Comment by blois** [comment]
Here's an example of it working: https://colab.research.google.com/gist/blois/3b36d0aa4c32d2ecc71e9208c32cf333/qgrid.ipynb

**Comment by keatonb** [comment]
> Here's an example of it working: https://colab.research.google.com/gist/blois/3b36d0aa4c32d2ecc71e9208c32cf333/qgrid.ipynb

It looks like this did work, but I can't get a qgrid widget to appear on Colab today.  Not with qgrid 1.1.1 or 1.3.1.  Anyone have a working example?
