### ISSUE TITLE
ModuleNotFoundError when attempting "jupyter labextension install qgrid2"

### ISSUE THREAD

**Issue by djakubiec** [quantopian/qgrid#351]
### Environment

* Operating System: macOS 11.1
* Python Version: Python 3.8.2
* How did you install Qgrid: pip install qgrid
* Python packages:
anyio==2.0.2
appnope==0.1.2
argon2-cffi==20.1.0
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
bleach==3.2.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
idna==2.10
ipykernel==5.4.3
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.2
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.2
jupyterlab==3.0.5
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.2
jupyterlab-widgets==1.0.0
jupytext==1.9.1
markdown-it-py==0.6.1
MarkupSafe==1.1.1
mdit-py-plugins==0.2.4
mistune==0.8.4
nbclassic==0.2.6
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.4.3
notebook==6.2.0
numpy==1.19.5
packaging==20.8
pandas==1.2.0
pandocfilters==1.4.3
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.9.0
prompt-toolkit==3.0.10
ptyprocess==0.7.0
pycparser==2.20
Pygments==2.7.4
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.5
PyYAML==5.3.1
pyzmq==21.0.1
qgrid==1.3.1
remote-ikernel==0.4.6
requests==2.25.1
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
terminado==0.9.2
testpath==0.4.4
toml==0.10.2
tornado==6.1
traitlets==5.0.5
urllib3==1.26.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1

* Jupyter lab packages (if applicable): 
JupyterLab v3.0.5
Other labextensions (built into JupyterLab)
   app dir: /Users/dan/Library/Python/3.8/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK
        jupyterlab-jupytext v1.3.0 enabled OK

And:

```
Known nbextensions:
   config dir: /Users/dan/.jupyter/nbconfig
     notebook section
       qgrid/extension  enabled
       - Validating: OK
       jupyter-js-widgets/extension  enabled
       - Validating: OK 

```
### Description of Issue
I tried to install the qgrid2 labextension per the docs:

```
> jupyter labextension install qgrid2
Building jupyterlab assets (production, minimized)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/q4/5t99lmrs5pn7fxcd6jc409k00000gn/T/jupyterlab-debug-ak9sqqhv.log

```
* What did you expect to happen?
For it to install qgrid2

* What happened instead?
Here is the error log:

```
> cat /var/folders/q4/5t99lmrs5pn7fxcd6jc409k00000gn/T/jupyterlab-debug-ak9sqqhv.log
Node v14.15.4

Yarn configuration loaded.
> /usr/local/bin/npm pack qgrid2
npm notice
npm notice 📦  qgrid2@1.1.3
npm notice === Tarball Contents ===
npm notice 1.2kB   package.json
npm notice 7.1kB   dist/00dd0ec0a16a1085e714c7906ff8fb06.png
npm notice 4.6kB   dist/093a819138276b446611d1d2a45b98a2.png
npm notice 851B    dist/097df1053ff3246e2f1af9d5a858ac6c.gif
npm notice 7.1kB   dist/0d6de499db574dd313c1f3500d337d1a.png
npm notice 6.3kB   dist/1e360be5458b462df279dadad6eee0cc.png
npm notice 830B    dist/2352874b5f636ca331fe9509a2f9bdd7.gif
npm notice 836B    dist/3e4484ea8db10af1320808c8477346ea.gif
npm notice 7.0kB   dist/40bf25799e4fec8079c7775083de09df.png
npm notice 4.7kB   dist/4e7e3e142f3939883cd0a7e00cabdaef.png
npm notice 846B    dist/6ccc1ed85229f7c88b07bbbeefe5214d.gif
npm notice 830B    dist/7e2ccbc3b7b736251403b238014dcacc.gif
npm notice 7.0kB   dist/853909d9945e29dd80d5c7d42f9b711e.png
npm notice 836B    dist/86586a919bd10f4cedba392f64336a54.gif
npm notice 833B    dist/8fcbe60e4efd8e2d1742bba8486994e1.gif
npm notice 846B    dist/9a52a923ceb5983fa0943c1e24d6d35b.gif
npm notice 7.0kB   dist/a4a8691ca395136aee475a56913b3456.png
npm notice 823B    dist/a92d8f6c106943995720f2884634670e.gif
npm notice 851B    dist/b2c868bfc2cab12122861c8214e38724.gif
npm notice 833B    dist/d104fcf119d40c51554ddb8b377142e5.gif
npm notice 7.0kB   dist/d10bc07005bb2d604f4905183690ac04.png
npm notice 4.6kB   dist/dc29114100c22b4660e3ec311004c1fd.png
npm notice 4.7kB   dist/e084661154ad58415fa1a8f54a04c5e9.png
npm notice 823B    dist/e38f33bbf55d6e20d21c4a10b9912668.gif
npm notice 6.3kB   dist/ea4ebe072be75fbbea002631916836de.png
npm notice 816.8kB dist/index.js
npm notice 2.5MB   dist/index.js.map
npm notice 454B    src/embed.js
npm notice 510B    src/extension.js
npm notice 255B    src/index.js
npm notice 386B    src/jupyterlab-plugin.js
npm notice 2.7kB   src/qgrid.booleanfilter.js
npm notice 14.5kB  src/qgrid.css
npm notice 4.9kB   src/qgrid.datefilter.js
npm notice 2.7kB   src/qgrid.editors.js
npm notice 5.8kB   src/qgrid.filterbase.js
npm notice 4.0kB   src/qgrid.sliderfilter.js
npm notice 11.2kB  src/qgrid.textfilter.js
npm notice 25.3kB  src/qgrid.widget.js
npm notice === Tarball Details ===
npm notice name:          qgrid2
npm notice version:       1.1.3
npm notice filename:      qgrid2-1.1.3.tgz
npm notice package size:  885.1 kB
npm notice unpacked size: 3.4 MB
npm notice shasum:        382a23fcfe0f3ff6cca7d3f81ea857951beefa5a
npm notice integrity:     sha512-skGlj1VoEOVgK[...]9aKkoXlcZCXZg==
npm notice total files:   39
npm notice
qgrid2-1.1.3.tgz

Node v14.15.4

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 3.31s.

> node /Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.59s.

> node /Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
(node:27736) [DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH] DeprecationWarning: MainTemplate.getAssetPath is deprecated (use Compilation.getAssetPath instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'base/js/dialog' in '/Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/src'
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1656:28
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:689:13
    at eval (eval at create (/Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:263:22
    at eval (eval at create (/Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:387:22
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:618:24
    at /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:762:5
    at finishWithoutResolve (/Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
resolve 'base/js/dialog' in '/Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/src'
  Parsed request is a module
  using description file: /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/src/node_modules doesn't exist or is not a directory
      looking for modules in /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/node_modules
        /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/qgrid2/node_modules/base doesn't exist
      /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules
        /Users/dan/Library/Python/3.8/share/jupyter/lab/staging/node_modules/base doesn't exist
      /Users/dan/Library/Python/3.8/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/dan/Library/Python/3.8/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/dan/Library/Python/3.8/share/node_modules doesn't exist or is not a directory
      /Users/dan/Library/Python/3.8/node_modules doesn't exist or is not a directory
      /Users/dan/Library/Python/node_modules doesn't exist or is not a directory
      /Users/dan/Library/node_modules doesn't exist or is not a directory
      /Users/dan/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/labextensions.py", line 132, in start
    build(clean_staging=self.should_clean,

  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/commands.py", line 463, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/Users/dan/Library/Python/3.8/lib/python/site-packages/jupyterlab/commands.py", line 675, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab

```
### Reproduction Steps

1. pip install qgrid
2. jupyter nbextension enable --py --user qgrid
3. jupyter labextension install qgrid2

### What steps have you taken to resolve this already?
Lots of Googling, uninstall, re-install, etc.

### Anything else?
No

**Comment by djakubiec** [comment]
In case it helps, I also tried to do a new/clean install via conda and got similar results.  Let me know if I can provide anything else, thanks!

I am using this conda environment:

```
name: jupyterlab3
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab >=3
  - jupytext
```

I followed that with:

```
⇒ conda install qgrid
<...omitted...>

⇒  conda list |grep qgrid
qgrid                     1.3.1                    py38_0

⇒  jupyter serverextension list ; echo '===' ; jupyter nbextension list ; echo '===' ; jupyter labextension list
config dir: /Users/dan/.jupyter
    jupytext  enabled
    - Validating...
      jupytext 1.9.1 OK
config dir: /Users/dan/opt/anaconda3/envs/jupyterlab3/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 3.0.5 OK
    jupytext  enabled
    - Validating...
      jupytext 1.9.1 OK
===
Known nbextensions:
  config dir: /Users/dan/.jupyter/nbconfig
    notebook section
      qgrid/extension  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      jupytext/index  enabled
      - Validating: OK
  config dir: /Users/dan/opt/anaconda3/envs/jupyterlab3/etc/jupyter/nbconfig
    notebook section
      jupytext/index  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      qgrid/extension  enabled
      - Validating: OK
===
JupyterLab v3.0.5
/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/labextensions
        jupyterlab-jupytext v1.3.0 enabled OK (python, jupytext)
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK (python, jupyterlab_widgets)
```

... and finally:

```
⇒  jupyter labextension install qgrid2
Building jupyterlab assets (production, minimized)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/q4/5t99lmrs5pn7fxcd6jc409k00000gn/T/jupyterlab-debug-13d_2jku.log

⇒  cat /var/folders/q4/5t99lmrs5pn7fxcd6jc409k00000gn/T/jupyterlab-debug-13d_2jku.log
Node v14.15.4

Yarn configuration loaded.
> /usr/local/bin/npm pack qgrid2
npm notice
npm notice 📦  qgrid2@1.1.3
npm notice === Tarball Contents ===
npm notice 1.2kB   package.json
npm notice 7.1kB   dist/00dd0ec0a16a1085e714c7906ff8fb06.png
npm notice 4.6kB   dist/093a819138276b446611d1d2a45b98a2.png
npm notice 851B    dist/097df1053ff3246e2f1af9d5a858ac6c.gif
npm notice 7.1kB   dist/0d6de499db574dd313c1f3500d337d1a.png
npm notice 6.3kB   dist/1e360be5458b462df279dadad6eee0cc.png
npm notice 830B    dist/2352874b5f636ca331fe9509a2f9bdd7.gif
npm notice 836B    dist/3e4484ea8db10af1320808c8477346ea.gif
npm notice 7.0kB   dist/40bf25799e4fec8079c7775083de09df.png
npm notice 4.7kB   dist/4e7e3e142f3939883cd0a7e00cabdaef.png
npm notice 846B    dist/6ccc1ed85229f7c88b07bbbeefe5214d.gif
npm notice 830B    dist/7e2ccbc3b7b736251403b238014dcacc.gif
npm notice 7.0kB   dist/853909d9945e29dd80d5c7d42f9b711e.png
npm notice 836B    dist/86586a919bd10f4cedba392f64336a54.gif
npm notice 833B    dist/8fcbe60e4efd8e2d1742bba8486994e1.gif
npm notice 846B    dist/9a52a923ceb5983fa0943c1e24d6d35b.gif
npm notice 7.0kB   dist/a4a8691ca395136aee475a56913b3456.png
npm notice 823B    dist/a92d8f6c106943995720f2884634670e.gif
npm notice 851B    dist/b2c868bfc2cab12122861c8214e38724.gif
npm notice 833B    dist/d104fcf119d40c51554ddb8b377142e5.gif
npm notice 7.0kB   dist/d10bc07005bb2d604f4905183690ac04.png
npm notice 4.6kB   dist/dc29114100c22b4660e3ec311004c1fd.png
npm notice 4.7kB   dist/e084661154ad58415fa1a8f54a04c5e9.png
npm notice 823B    dist/e38f33bbf55d6e20d21c4a10b9912668.gif
npm notice 6.3kB   dist/ea4ebe072be75fbbea002631916836de.png
npm notice 816.8kB dist/index.js
npm notice 2.5MB   dist/index.js.map
npm notice 454B    src/embed.js
npm notice 510B    src/extension.js
npm notice 255B    src/index.js
npm notice 386B    src/jupyterlab-plugin.js
npm notice 2.7kB   src/qgrid.booleanfilter.js
npm notice 14.5kB  src/qgrid.css
npm notice 4.9kB   src/qgrid.datefilter.js
npm notice 2.7kB   src/qgrid.editors.js
npm notice 5.8kB   src/qgrid.filterbase.js
npm notice 4.0kB   src/qgrid.sliderfilter.js
npm notice 11.2kB  src/qgrid.textfilter.js
npm notice 25.3kB  src/qgrid.widget.js
npm notice === Tarball Details ===
npm notice name:          qgrid2
npm notice version:       1.1.3
npm notice filename:      qgrid2-1.1.3.tgz
npm notice package size:  885.1 kB
npm notice unpacked size: 3.4 MB
npm notice shasum:        382a23fcfe0f3ff6cca7d3f81ea857951beefa5a
npm notice integrity:     sha512-skGlj1VoEOVgK[...]9aKkoXlcZCXZg==
npm notice total files:   39
npm notice
qgrid2-1.1.3.tgz

Node v14.15.4

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 12.53s.

> node /Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> node /Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@jupyterlab/json-extension > react-json-tree@0.12.1" has incorrect peer dependency "react-dom@^16.3.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper@1.3.7" has incorrect peer dependency "react@0.14.x || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/ui-components > @blueprintjs/core > react-popper > create-react-context@0.3.0" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.5.3" has unmet peer dependency "crypto@1.0.1".
[5/5] Building fresh packages...
Done in 3.27s.

> node /Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
(node:32388) [DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH] DeprecationWarning: MainTemplate.getAssetPath is deprecated (use Compilation.getAssetPath instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'base/js/dialog' in '/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/qgrid2/src'
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1656:28
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:689:13
    at eval (eval at create (/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:263:22
    at eval (eval at create (/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:387:22
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:118:11
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:618:24
    at /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:762:5
    at finishWithoutResolve (/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
resolve 'base/js/dialog' in '/Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/qgrid2/src'
  Parsed request is a module
  using description file: /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/qgrid2/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/qgrid2/src/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/qgrid2/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules
        /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/staging/node_modules/base doesn't exist
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/jupyter/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/jupyterlab3/share/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/jupyterlab3/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/envs/node_modules doesn't exist or is not a directory
      /Users/dan/opt/anaconda3/node_modules doesn't exist or is not a directory
      /Users/dan/opt/node_modules doesn't exist or is not a directory
      /Users/dan/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 132, in start
    build(clean_staging=self.should_clean,

  File "/Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/commands.py", line 463, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/Users/dan/opt/anaconda3/envs/jupyterlab3/lib/python3.8/site-packages/jupyterlab/commands.py", line 675, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab
```

**Comment by aguileraGit** [comment]
Ran into the same issue after updating JupyterLab 3.0.5. Maybe related to #350?

**Comment by timfeirg** [comment]
getting the same error at jupyterlab 3.0.14

**Comment by Lawrencelapointe** [comment]
Same error stream.

can avoid the build error by:
$ jupyter labextension uninstall qgrid2

build goes through no problem.

**Comment by MatCast** [comment]
Getting the same error here

**Comment by sparklie3** [comment]
Seeing similar error on jupyterlab 3.1.2

**Comment by info-rchitect** [comment]
All of us frustrated `qgrid` users should figure out who can support it, [possibly add](https://github.com/jupyter-widgets/ipywidgets/issues/3240) `qgrid` as a default `ipywidget`?

**Comment by lukasValentin** [comment]
Run into the same problem on jupyterlab 3.0.16

**Comment by OrangeEfficiency** [comment]
I'm getting the same error on 3.0.14. Has anyone found a solution to this ?

**Comment by paulochf** [comment]
Bump. Just ran into this issue.

Operating System: `macOS 11.1`
Python Version: `3.7.10`

Jupyter:
```
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyterlab==3.4.4
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
jupyterlab-widgets==1.1.1
```

**Comment by StepOITD** [comment]
emmm, its 2023 already, and we still have this problem unsolved？
someone save me please

**Comment by ankostis** [comment]
There is a new QGrid "fork" (the same codebase just not git-cloned) that works with all latest jupyter machinery, minus `ipywidgets-8+`:

https://github.com/JohnOmernik/qgrid

It was packaged with all NPM dependencies in wheels, and works out of the box.
