### ISSUE TITLE
Here, working version

### ISSUE THREAD

**Issue by skapin** [quantopian/qgrid#383]
I made a working conda version for ipywidget 8 and jupyter lab 3.x

https://anaconda.org/eshard/qgrid

**Comment by ankostis** [comment]
Interesting that it works with `ipywidget-8`, JohnOmernik/qgrid#9 managed to run for pre-8 widgets, what did you change?

**Comment by skapin** [comment]
- Reworked the plugin using cookie cutter
- copy/paste src code
- follow migration guide about migrating to ipywidget8 (changer js and py files mainly)

**Comment by huyuhuster** [comment]
Does it work with Voila too?

**Comment by skapin** [comment]
Didnt test but perhpase I guess ?

**Comment by huyuhuster** [comment]
When I try to use qgrid with Voila, I get some error like this:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'QgridModel' from module 'qgrid'
Error: Script error for "qgrid"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (http://202.122.32.111:8060/voila/static/require.min.js:1:1067)
    at HTMLScriptElement.onScriptError (http://202.122.32.111:8060/voila/static/require.min.js:1:13218)
```
The version I used:
jupyter                 1.0.0
jupyter_client          7.3.4
jupyter_core            5.2.0
jupyter-server          1.23.4
jupyterlab              3.5.3
jupyterlab-server       2.10.3
jupyterlab-widgets      3.0.5
ipywidgets              8.0.4
voila                   0.4.0

**Comment by ankostis** [comment]
How did you install it?
If you followed [Omnerik's instructions](https://github.com/JohnOmernik/qgrid), it won't work with `ipywidgets >= 8`.

**Comment by huyuhuster** [comment]
I install it by: 
    `conda install -c eshard qgrid`

**Comment by skapin** [comment]
Ok so it doesnt work with voila  :/
With your output I have no clue like that :/

**Comment by ankostis** [comment]
Can you try to downgrade `pip install "ipywidgets<8'`?

**Comment by ankostis** [comment]
I compared the py sources between Omerik's version which is `ipywidget-8+` incompatible (see above) and @skapin 's conda package, and i see no significant difference - i guess it is ALSO `ipywidget-8+` incompatible :-(

**Comment by skapin** [comment]
i works with pywidget8, but doenst works with voila,it's a different issue

**Comment by ankostis** [comment]
Can you please paste here your output for this command (or `conda list` if on _conda_)?

```bash
pip list | grep -iE "jupy|ipython|note|qgrid|ipy|js"
```
