### ISSUE TITLE
pip install no longer works

### ISSUE THREAD

**Issue by marcomayer** [quantopian/qgrid#64]
Hi there,

since a few days (guess new release) I get this when doing my standard upgrade-check on the module (using latest anaconda 3.5 on latest mac osx). 

| => pip install qgrid --upgrade --no-deps

```
Collecting qgrid
  Using cached qgrid-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bs/gk3rhfzd2475g9vx5wlcqqb40000gn/T/pip-build-lq0rtygo/qgrid/setup.py", line 27, in <module>
        reqs = read_requirements('requirements.txt')
      File "/private/var/folders/bs/gk3rhfzd2475g9vx5wlcqqb40000gn/T/pip-build-lq0rtygo/qgrid/setup.py", line 24, in read_requirements
        with open(reqs_file) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/bs/gk3rhfzd2475g9vx5wlcqqb40000gn/T/pip-build-lq0rtygo/qgrid/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/bs/gk3rhfzd2475g9vx5wlcqqb40000gn/T/pip-build-lq0rtygo/qgrid
```

**Comment by ssanderson** [comment]
@marcomayer there was an issue with how we uploaded v0.3.0 to PyPI.  I just pushed v0.3.1 which fixes this issue.

Sorry for the mixup.

**Comment by marcomayer** [comment]
thanks a lot anderson, it works just fine now! :+1:
